#!/usr/bin/env bash
#

#A script to show current power profile

declare -A profiles=( [performance]= [balanced]= [power-saver]= )

current_profile=$(/usr/bin/powerprofilesctl get)
echo ${profiles[$current_profile]}
